# Generated by Django 3.2.7 on 2021-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histor',
            new_name='History',
        ),
    ]
